---
dataset: koHateSpeech
classifier: mbert
computer: labo
split: 1
dataset_size: 1500
algo: VAE
random_seed: 7
selector: random
max_seq_length: 32
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 20
batch_size_classifier: 16

tokenizer: "tweetTokenizer"

hidden_size_algo: 2048
word_dropout: 0.6
dropout_algo: 0.6
latent_size: 15
embeddings: None
freeze_embeddings: False
tie_embeddings: False
tie_encoders: False
nb_epoch_algo: 30
x0: 15
sampling_strategy: random