---
dataset: CLS
classifier: mbert
computer: labo
split: 1
dataset_size: 1000
algo: AEDA
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False

prob_reg: 0.5
tokenizer: "tweetTokenizer"

nb_epoch_classifier: 20
batch_size_classifier: 16