---
dataset: Swahili
classifier: mbertAEDA
computer: labo
split: 0 #1
dataset_size: 1000
algo: AEDA
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False


tokenizer: "tweetTokenizer"
prob_reg: 0.5

hidden_size_classifier: 1024
embed_size_classifier: 300
num_layers_classifier: 2
dropout_classifier: 0.3
nb_epoch_classifier: 30 #15
batch_size_classifier: 16