---
dataset: Swahili
classifier: mbert
computer: labo
split: 1
dataset_size: 1000
algo: BacktranslationT5
random_seed: 7
selector: random
max_seq_length: 32
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 15
batch_size_classifier: 16

lan_to: en
#
#nb_epoch_algo: 10
#learning_rate: 0.00005
#batch_size_algo: 32
