---
dataset: CLS
classifier: mbert
computer: labo
split: 1
dataset_size: 1500
algo: mCBERT
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 15
batch_size_classifier: 16

tokenizer: "tweetTokenizer"

nb_epoch_algo: 4
learning_rate: 0.00005
batch_size_algo: 4
