---
dataset: IronyB
classifier: Bert
computer: labo
split: 10
dataset_size: 50
algo: GPT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 35

batch_size_classifier: 64

batch_size_algo: 16
num_epoch_algo: 50
