---
dataset: koHateSpeech
classifier: mbert
computer: labo
split: 1
dataset_size: 100
algo: BacktranslationT5
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 15
batch_size_classifier: 16

tokenizer: "tweetTokenizer"
lan_to: en