---
dataset: SB10k
classifier: mbertAEDA #mbert
computer: labo
split: 0 #1
dataset_size: 100
algo: AEDA
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 70 #35
batch_size_classifier: 16

prob_reg: 0.5
tokenizer: "tweetTokenizer"