---
dataset: CLS
classifier: mbertAEDA
computer: labo
split: 1
dataset_size: 100
algo: BacktranslationT5
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 30 #20
batch_size_classifier: 16

tokenizer: "tweetTokenizer"
prob_reg: 0.5

lan_to: en
fix_dataset: False