---
dataset: CLS
classifier: mbert
computer: labo
split: 1
dataset_size: 100
algo: mCBERT
random_seed: 7
selector: random
max_seq_length: 32
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 30 #20
batch_size_classifier: 32

tokenizer: "tweetTokenizer"
prob_reg: 0.5

nb_epoch_algo: 4
learning_rate: 0.00005
batch_size_algo: 4

fix_dataset: False