---
dataset: CLS
classifier: mbert
computer: labo
split: 1
dataset_size: 100
algo: PAE
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 20
batch_size_classifier: 32

prob_reg: 0.5
tokenizer: "tweetTokenizer" #"mwordPiece"
strat_pretraining: "autoencoder"

nb_epoch_algo_pretraining: 10
hidden_size_algo: 4096
word_dropout: 0.3
dropout_algo: 0.3
latent_size: 512
embeddings: None
freeze_embeddings: False
tie_embeddings: False
tie_encoders: False
nb_epoch_algo: 30
x0: 15
sampling_strategy: random