---
dataset: Swahili
classifier: mbert
computer: labo
split: 1
dataset_size: 100
algo: mCBERT
random_seed: 7
selector: random
max_seq_length: 32
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 50
batch_size_classifier: 16

nb_epoch_algo: 4
learning_rate: 0.00005
batch_size_algo: 8

tokenizer: "tweetTokenizer"
fix_dataset: False