---
dataset: CLS
classifier: mbertAEDA
computer: labo
split: 0
dataset_size: 500
algo: dummy
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 10 #20
batch_size_classifier: 16

tokenizer: "tweetTokenizer"
prob_reg: 0.5
