---
dataset: SB10k
classifier: mbertAEDA
computer: labo
split: 0 #1
dataset_size: 0
algo: AEDA
random_seed: 7
selector: random
max_seq_length: 64
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 30 #15
batch_size_classifier: 16

prob_reg: 0.5
tokenizer: "tweetTokenizer"